[package]
name = "openmat-solve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sundials"]
sundials = ["dep:sundials-sys"]

[dependencies]
sundials-sys = { version = "0.5", features = ["build_libraries"], optional = true }
